version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    external: true
